spring.application.name=P01_SpringSecurityArchitecture

logging.level.org.springframework.security=INFO

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/p01_security_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret-key=${AUTH_SECRET:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3ODgzNTQxODgsImV4cCI6MTc4ODM1Nzc4OCwianRpIjoiYjEzOTJjNmUtOTUyZi00YzI2LWIyZWEtY2UwNGJjMjIzMzgxIiwiaXNzIjoiYXBpLmV4YW1wbGUuY29tIiwic3ViIjoidXNlcl82MTcwIiwiYXVkIjoiaHR0cHM6Ly9leGFtcGxlLmNvbSJ9.xghXMKvIivK8jN1ZKMu7O7TKjOGW2xtiaFI1TZrq2-c}
jwt.expiration-time=${JWT_EXPIRATION_TIME:900000}
