spring.application.name=P01_ConsumerService
server.port=8080

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=order-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.P01_ConsumerService.dto.OrderConsumer
