spring.application.name=P01_EntityMappingBasic
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/p01_entity_mapping_basic
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true