spring.application.name=P02_EntityLifeCycle
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/p02_jpa_practice
spring.datasource.username=${JPA_LIFECYCLE_DB_USERNAME:postgres}
spring.datasource.password=${JPA_LIFECYCLE_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
